### ISSUE TITLE
MySQL | Update sql file

### ISSUE THREAD

**Issue by GrapesGoober** [GrapesGoober/TodoCards-Project#11]
# Problem
We've done some redesigns for our app, so it'll be nice to update our mysql database to reflect such changes. Currently those changes only exist on the nanoni branch.
# Solution
- [x] Rewrite & check our data that it's up-to-date with our new goals
- [x] Insert some sample data
   - [x] Decks, cards, subcards, access (no need for any sharecode yet)
   - [x] For user, use the `hash_password` function in `user.py`
       - You have to generate a bunch of password hashes first.
       - Refer to issue #12 for more info
- [x] Test queries on some sample data (make sure it works)
# Workflow
- [x] Do this onto your branch
- [x] Once finished, open a pull request to `Grapes-Setup-Project` branch. I'll review your code.

**Comment by NanoniPck** [comment]
กดดัน
