### ISSUE TITLE
Generate sample password hashes

### ISSUE THREAD

**Issue by GrapesGoober** [GrapesGoober/TodoCards-Project#12]
# Problem
Since we'd be using a secure "salt-hash" function to store our passwords, as opposed to plain text, we need to be a bit more careful with how we insert our password in our sample users. Here's the idea:

# Solution
- [x] In a python script, use the `hash_password()` function in `user.py` to generate some password hashes. This represent a secure way to store passwords.
- [x] When inserting to user table (as sample data), use this hashes instead of raw passwords
- [x] And **PLEASE** comment these username-passwords here as well, so that we won't forget them

**Comment by NanoniPck** [comment]
ajarn ajarn123

bob bob123

cindy cindy123 

dean dean123 

fay fay123
