### ISSUE TITLE
Backend | Implement access checker functions

### ISSUE THREAD

**Issue by GrapesGoober** [GrapesGoober/TodoCards-Project#15]
# Problem
The design of our app is that some users can have only certain access to certain decks, cards, & subcards. Implement this logic in python, in `cards.py` and `decks.py`
# Solution
- [x] implement the deck check access functions in the `decks.py`
  - This essentially checks whether a username has access to a deck
- [x] implement the card & subcard check access functions in the `cards.py`
  - This essentially checks whether a username has access to certain cards or subcards
# Suggestion
I think it could be easier if you nested some functions together. For example, to check access for a subcard, you use sql query to get that subcard's card_id, then use the card's check access function. The card's check access function can then recursively do the same thing (i.e. retrieve deckid of that card, then use deck's check access function again). This should simplify mental workload a bit, but hey, each to their own.

**Comment by NanoniPck** [comment]
เสดด check access for deck, card n subcard (Nachat also did the test cases)
