### ISSUE TITLE
BackEnd | Access functions

### ISSUE THREAD

**Issue by GrapesGoober** [GrapesGoober/TodoCards-Project#48]
# Problem
Many users can have different access mappings to each decks. Need to implement access functions
# To do
- [x] Add access function: recieve a deckId, accessType, and username as arguments. For example
```
def addAccess(mydb, deckId, accessType, username):
```
Note that this will not generate a duplicate access record when another already exists. If the target access already exists, simply do nothing and return true. (also, this function **does not need to check access for the access giver**. Since this function will be used only by `create_deck` and `recieve_sharecode`, both of these functions will check the giver's access beforehand)

- [x] Remove access: recieves a deckId, removee's username and remover's username as arguments.
```
def removeAccess(mydb, deckId, removee_username, remover_username):
```
This needs to check for remover's username access (whether he/she still has the edit access to remove someone else's access). If the remover's username doesn't pass access check, return false. If the access is already removed (i.e. it doesn't exist) simply do nothing and return true.

- [x] The addAccess function goes into the create deck. The create deck function will recieve deckInfo and accessInfo. The accessInfo will look like below. Simply loop through each item and call the addAccess for each item:
```
{
  "bob": "view",
  "cindy": "edit"
}
```

**Comment by NanoniPck** [comment]
done
