### ISSUE TITLE
FrontEnd | Modify the edit / delete UI?

### ISSUE THREAD

**Issue by GrapesGoober** [GrapesGoober/TodoCards-Project#49]
# Problem
Currently, the UI edit & delete are scattered. I came up with a way that might be a little easier...
# Idea
What I came up with is that, in the card page, there is a edit button at the top (for editing deck) and each card item will have editing icon (to edit each individual cards). Delete button will be included inside these edit modals. For example:
- To edit deck, click on the deck to go to that card page, then click on the edit icon up top
  - If you want to delete, the button will be found inside the modal
- To edit card, go to card page, click on specific card, then click edit icon
  - If you want to delete, the button will be found inside the modal
- To edit subcard, click on the card (which will show subcard list, which you can then edit the subcard)
  - To delete, click finish subcard, which the edit icon will now change to delete icon

**Comment by awacado** [comment]
Can I add the edit button in the card page(inside a deck) at the bottom-left instead?

**Comment by awacado** [comment]
Because at the top right, we'll have the share button.

**Comment by awacado** [comment]
@GrapesGoober

**Comment by GrapesGoober** [comment]
@awacado I think maybe we can
- Put them next together (on top right)
- Put the share UI inside the edit UI (i think it's better)
- Put the edit at the bottom left and share at top right (i think it's a little inconsistent)

I prefer option 2

**Comment by GrapesGoober** [comment]
Ok, we're going with this
