### ISSUE TITLE
Backend | Get access list

### ISSUE THREAD

**Issue by GrapesGoober** [GrapesGoober/TodoCards-Project#58]
# Problem
In the "edit deck" interface, the user will have a list of usernames that currently has access to this deck. However, there isn't yet a backend implementation to "get access list" yet
# Solution
Implement the "get access list" function. 
- Should take deckId as arguments
- No need to check access before returning
Function header should look like
```
def get_access_list(mydb, deck_id)
```
Return should look like
```
{
  "edit" : [ "john", "jenny", "jack" ],
  "view" : [ "gappie", "bub", "booboo"] 
}
```
If there are no user that satisfies that particular access, just return empty list (but NOT empty dict!)
```
{
  "edit" : [  ], # in this example, there are nobody who can edit this deck
  "view" : [ "gappie", "bub", "booboo"] 
}
```

**Comment by NanoniPck** [comment]
Mysql

ในวันที่ ศ. 17 พ.ย. 2023 เวลา 13:53 Graps ***@***.***>
เขียนว่า:

**Comment by NanoniPck** [comment]
done by nachat

**Comment by NanoniPck** [comment]
done by grappi
